@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.tysontheember.apertureapi.path;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;
